# Generated by Django 3.2.6 on 2021-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_avt',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
