# Generated by Django 3.2.5 on 2021-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='LeFan', max_length=50, unique=True),
        ),
    ]
