# Generated by Django 3.2.6 on 2021-08-13 03:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviewscount',
            name='date_view',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='postviewscount',
            unique_together={('post', 'user', 'date_view'), ('post', 'ip', 'date_view')},
        ),
    ]
