# Generated by Django 3.2.5 on 2021-08-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like_reviewrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
