# Generated by Django 3.2.6 on 2021-08-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210813_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postinteract',
            old_name='post_id',
            new_name='post',
        ),
    ]
