# Generated by Django 3.2.6 on 2021-08-22 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_alter_postinteract_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInteract_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user_dislikes', models.ManyToManyField(related_name='requirement_post_dislikes', to=settings.AUTH_USER_MODEL)),
                ('user_likes', models.ManyToManyField(related_name='requirement_post_likes', to=settings.AUTH_USER_MODEL)),
                ('user_shares', models.ManyToManyField(related_name='requirement_post_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
