# Generated by Django 3.2.6 on 2021-08-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postinteract_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinteract',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='postinteract',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postinteract',
            name='shares',
        ),
    ]
