# Generated by Django 3.2.6 on 2021-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='left',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='right',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
